// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd8VDeU452vCpmumSw3iFssRv-hgVgy9s',
    appId: '1:335324257275:web:98e14f485ff80d3e71095e',
    messagingSenderId: '335324257275',
    projectId: 'smart-muslim-ad4f6',
    authDomain: 'smart-muslim-ad4f6.firebaseapp.com',
    storageBucket: 'smart-muslim-ad4f6.firebasestorage.app',
    measurementId: 'G-7RV8X7VNGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgfja-gR4E6OMw00Skvz6iSYWrsUgqoJg',
    appId: '1:335324257275:android:57446f3c43a8823271095e',
    messagingSenderId: '335324257275',
    projectId: 'smart-muslim-ad4f6',
    storageBucket: 'smart-muslim-ad4f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBbIggnTXiUg6_KD5bx3navUr8nWynsWo',
    appId: '1:335324257275:ios:26679b17d3c2887b71095e',
    messagingSenderId: '335324257275',
    projectId: 'smart-muslim-ad4f6',
    storageBucket: 'smart-muslim-ad4f6.firebasestorage.app',
    iosBundleId: 'com.smartmuslim.app.smartMuslim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBbIggnTXiUg6_KD5bx3navUr8nWynsWo',
    appId: '1:335324257275:ios:26679b17d3c2887b71095e',
    messagingSenderId: '335324257275',
    projectId: 'smart-muslim-ad4f6',
    storageBucket: 'smart-muslim-ad4f6.firebasestorage.app',
    iosBundleId: 'com.smartmuslim.app.smartMuslim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd8VDeU452vCpmumSw3iFssRv-hgVgy9s',
    appId: '1:335324257275:web:b617fc2fa6a261c971095e',
    messagingSenderId: '335324257275',
    projectId: 'smart-muslim-ad4f6',
    authDomain: 'smart-muslim-ad4f6.firebaseapp.com',
    storageBucket: 'smart-muslim-ad4f6.firebasestorage.app',
    measurementId: 'G-XKNFJND8YB',
  );
}
